# Generated by Django 3.0.8 on 2020-07-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagebazarclone', '0002_auto_20200727_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='media/imagebazarclone/images/'),
        ),
    ]
